// resources/js/Pages/Auth/Login.vue
<template>
    <div class="min-h-screen bg-gray-50 flex items-center justify-center">
        <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-primary-600">ChatCX</h1>
                <p class="text-gray-500 mt-2">تسجيل الدخول إلى لوحة التحكم</p>
            </div>

            <div v-if="$page.props.errors?.email" class="bg-red-50 text-red-600 p-3 rounded mb-4 text-sm">
                {{ $page.props.errors.email }}
            </div>

            <form @submit.prevent="login">
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-medium mb-2">البريد الإلكتروني</label>
                    <input type="email" v-model="form.email" required
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500">
                </div>

                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-medium mb-2">كلمة المرور</label>
                    <input type="password" v-model="form.password" required
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500">
                </div>

                <button type="submit" :disabled="loading"
                    class="w-full bg-primary-600 text-white py-2 rounded-lg hover:bg-primary-700 transition disabled:opacity-50">
                    {{ loading ? 'جاري تسجيل الدخول...' : 'تسجيل الدخول' }}
                </button>
            </form>

            <p class="text-center mt-4 text-sm text-gray-500">
                ليس لديك حساب؟
                <Link href="/register" class="text-primary-600 hover:text-primary-700">إنشاء حساب جديد</Link>
            </p>
        </div>
    </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { Link, router } from '@inertiajs/vue3'

const loading = ref(false)
const form = reactive({ email: '', password: '' })

function login() {
    loading.value = true
    router.post('/login', form, {
        onFinish: () => { loading.value = false }
    })
}
</script>

// src/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";

export default function LoginPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    const formData = new FormData(e.currentTarget);
    const email = formData.get("email") as string;
    const password = formData.get("password") as string;

    try {
      const result = await signIn("credentials", {
        email,
        password,
        redirect: false,
      });

      if (result?.error) {
        setError("البريد الإلكتروني أو كلمة المرور غير صحيحة");
        return;
      }

      router.push("/dashboard");
      router.refresh();
    } catch {
      setError("حدث خطأ أثناء تسجيل الدخول");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-950 p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="flex justify-center mb-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-white text-lg font-bold">CX</div>
          </div>
          <CardTitle className="text-2xl">تسجيل الدخول</CardTitle>
          <CardDescription>أدخل بريدك الإلكتروني وكلمة المرور</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-4">
            {error && (
              <div className="rounded-lg bg-red-50 dark:bg-red-900/20 p-3 text-sm text-red-600 dark:text-red-400">
                {error}
              </div>
            )}
            <div className="space-y-2">
              <label className="text-sm font-medium">البريد الإلكتروني</label>
              <Input
                name="email"
                type="email"
                required
                placeholder="your@email.com"
                dir="ltr"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">كلمة المرور</label>
              <Input
                name="password"
                type="password"
                required
                placeholder="••••••••"
                dir="ltr"
              />
            </div>
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? "جاري تسجيل الدخول..." : "تسجيل الدخول"}
            </Button>
            <p className="text-center text-sm text-gray-500">
              ليس لديك حساب؟{" "}
              <Link href="/register" className="text-primary hover:underline">
                إنشاء حساب
              </Link>
            </p>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
