// resources/js/Pages/Auth/Register.vue
<template>
    <div class="min-h-screen bg-gray-50 flex items-center justify-center">
        <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-lg">
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-primary-600">ChatCX</h1>
                <p class="text-gray-500 mt-2">إنشاء حساب جديد لخدمة العملاء</p>
            </div>

            <form @submit.prevent="register">
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-medium mb-2">اسم المتجر</label>
                    <input type="text" v-model="form.store_name" required
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-medium mb-2">الاسم</label>
                    <input type="text" v-model="form.name" required
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-medium mb-2">البريد الإلكتروني</label>
                    <input type="email" v-model="form.email" required
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-medium mb-2">رقم الجوال</label>
                    <input type="tel" v-model="form.phone"
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-medium mb-2">كلمة المرور</label>
                    <input type="password" v-model="form.password" required minlength="8"
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                </div>

                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-medium mb-2">تأكيد كلمة المرور</label>
                    <input type="password" v-model="form.password_confirmation" required
                        class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                </div>

                <button type="submit" :disabled="loading"
                    class="w-full bg-primary-600 text-white py-2 rounded-lg hover:bg-primary-700 transition disabled:opacity-50">
                    {{ loading ? 'جاري إنشاء الحساب...' : 'إنشاء الحساب' }}
                </button>
            </form>

            <p class="text-center mt-4 text-sm text-gray-500">
                لديك حساب بالفعل؟
                <Link href="/login" class="text-primary-600 hover:text-primary-700">تسجيل دخول</Link>
            </p>
        </div>
    </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { Link, router } from '@inertiajs/vue3'

const loading = ref(false)
const form = reactive({
    store_name: '',
    name: '',
    email: '',
    phone: '',
    password: '',
    password_confirmation: '',
})

function register() {
    loading.value = true
    router.post('/register', form, {
        onFinish: () => { loading.value = false }
    })
}
</script>

// src/app/register/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";

export default function RegisterPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    const formData = new FormData(e.currentTarget);
    const data = {
      email: formData.get("email") as string,
      password: formData.get("password") as string,
      name: formData.get("name") as string,
      storeName: formData.get("storeName") as string,
    };

    if (data.password.length < 8) {
      setError("كلمة المرور يجب أن تكون 8 أحرف على الأقل");
      setIsLoading(false);
      return;
    }

    try {
      const res = await fetch("/api/auth/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });

      const result = await res.json();

      if (!res.ok) {
        setError(result.error || "حدث خطأ أثناء التسجيل");
        return;
      }

      router.push("/login?registered=true");
    } catch {
      setError("حدث خطأ في الاتصال");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-950 p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="flex justify-center mb-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-white text-lg font-bold">CX</div>
          </div>
          <CardTitle className="text-2xl">إنشاء حساب جديد</CardTitle>
          <CardDescription>ابدأ تجربتك المجانية لمدة 14 يومًا</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-4">
            {error && (
              <div className="rounded-lg bg-red-50 dark:bg-red-900/20 p-3 text-sm text-red-600 dark:text-red-400">
                {error}
              </div>
            )}
            <div className="space-y-2">
              <label className="text-sm font-medium">الاسم الكامل</label>
              <Input name="name" required placeholder="محمد أحمد" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">اسم المتجر</label>
              <Input name="storeName" required placeholder="متجري الإلكتروني" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">البريد الإلكتروني</label>
              <Input name="email" type="email" required placeholder="your@email.com" dir="ltr" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">كلمة المرور</label>
              <Input name="password" type="password" required placeholder="•••••••• (8 أحرف minimum)" dir="ltr" />
            </div>
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? "جاري إنشاء الحساب..." : "إنشاء الحساب"}
            </Button>
            <p className="text-center text-sm text-gray-500">
              لديك حساب بالفعل؟{" "}
              <Link href="/login" className="text-primary hover:underline">
                تسجيل الدخول
              </Link>
            </p>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
